name: "Automatic Merge"

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  merge:
    name: "Merge Pull Requests"
    runs-on: ubuntu-latest

    steps:
    - name: "Merge"
      uses: "nucleos/auto-merge-action@1.2.0"
      env:
        "GITHUB_TOKEN": ${{ secrets.ORGANIZATION_ADMIN_TOKEN }}
