name: 'Documentation'

on:
  create:
  push:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  build:
    name: 'Build RST'

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2.3.0
        with:
          python-version: '3.7'

      - name: "Display Python version"
        run: python -c "import sys; print(sys.version)"

      - name: "Cache pip"
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "Install custom requirements via pip"
        run: pip install -r docs/requirements.txt

      - name: "Build documentation"
        run: sphinx-build -W -b html -d _build/doctrees docs _build/html

  doctor-rst:
    name: 'DOCtor-RST'

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      - name: "Run DOCtor-RST"
        uses: docker://oskarstark/doctor-rst
        with:
          args: --short
        env:
          DOCS_DIR: 'docs/'
